version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faker
    versions:
    - 5.4.0
    - 5.5.0
    - 5.5.1
    - 5.5.2
  - dependency-name: socket.io-client
    versions:
    - 4.0.0
  - dependency-name: socket.io
    versions:
    - 4.0.0
